<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-02-11 22:01

$extensionPath = t3lib_extMgm::extPath('stg_clearcache');
return array(
	'tx_stgclearcache' => $extensionPath . 'class.tx_stgclearcache.php',
);
?>